version: '3.1'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ssd
      MYSQL_ROOT_PASSWORD: ssd
      MYSQL_USER: ssd
      MYSQL_PASSWORD: ssd